require("dotenv").config();
const express = require("express");
const crypto = require("crypto");
const Razorpay = require("razorpay");
const app = express();
app.use(express.json());
app.use(express.static("public"));
const PORT = process.env.PORT || 10000;
const HOST = process.env.HOST || "0.0.0.0";
const MERCHANT_NAME = process.env.MERCHANT_NAME || "PAYPILOT Demo Store";
const razorpay = process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET ? new Razorpay({key_id: process.env.RAZORPAY_KEY_ID,key_secret: process.env.RAZORPAY_KEY_SECRET}) : null;
const sessions = new Map(); const audit = [];
const POLICY = {maxDiscountPercent:15,maxOfferAmountPaise:500000,currency:"INR"};
function auditLog(type,action,details={}){const entry={id:crypto.randomUUID(),timestamp:new Date().toISOString(),type,action,details};audit.unshift(entry);return entry;}
function analyzeIntent(message){const text=String(message||"").toLowerCase();let intent="BROWSING",confidence=.72,signals=["general product interest"];if(/buy|purchase|checkout|order|need|want|looking for/.test(text)){intent="PURCHASE_READY";confidence=.93;signals=["purchase language","high commercial intent"]}else if(/price|cost|expensive|cheap|discount|deal|offer/.test(text)){intent="PRICE_SENSITIVE";confidence=.89;signals=["price concern","offer sensitivity"]}else if(/compare|vs|versus|which|better/.test(text)){intent="EVALUATING";confidence=.84;signals=["comparison language","decision stage"]}const result={intent,confidence,signals};auditLog("AI","INTENT_ANALYZED",{message,result});return result;}
function generateOffer(intent){let discountPercent=5,reason="Small incentive to reduce purchase friction.";if(intent==="PURCHASE_READY"){discountPercent=10;reason="Customer shows strong purchase intent; a limited incentive can accelerate checkout."}else if(intent==="PRICE_SENSITIVE"){discountPercent=15;reason="Customer signals price sensitivity; use the maximum bounded discount to protect margin."}else if(intent==="EVALUATING"){discountPercent=7;reason="Customer is comparing options; a moderate incentive can encourage conversion."}const base=499900;const offer={offerId:crypto.randomUUID(),baseAmountPaise:base,discountPercent,discountPaise:Math.round(base*discountPercent/100),finalAmountPaise:Math.round(base*(1-discountPercent/100)),currency:"INR",reason,guardrails:{maxDiscountPercent:POLICY.maxDiscountPercent,maxOfferAmountPaise:POLICY.maxOfferAmountPaise,requiresMerchantApproval:true}};auditLog("AI","OFFER_GENERATED",offer);return offer;}
app.get("/health",(_req,res)=>res.json({status:"ok",service:"PAYPILOT AI"}));
app.get("/api/config",(_req,res)=>res.json({merchantName:MERCHANT_NAME,razorpayKeyId:process.env.RAZORPAY_KEY_ID||"",testMode:true,policy:POLICY}));
app.post("/api/analyze",(req,res)=>{const {message}=req.body;if(!message||message.trim().length<3)return res.status(400).json({error:"Customer message is required."});const intent=analyzeIntent(message),offer=generateOffer(intent.intent),sessionId=crypto.randomUUID();sessions.set(sessionId,{sessionId,message,intent,offer,approval:null,payment:null,createdAt:new Date().toISOString()});auditLog("WORKFLOW","SESSION_CREATED",{sessionId});res.json({sessionId,intent,offer});});
app.post("/api/approve",(req,res)=>{const {sessionId,approved}=req.body,session=sessions.get(sessionId);if(!session)return res.status(404).json({error:"Session not found."});session.approval={approved:Boolean(approved),approvedAt:new Date().toISOString()};auditLog("MERCHANT",approved?"OFFER_APPROVED":"OFFER_REJECTED",{sessionId,offerId:session.offer.offerId,approved});res.json({sessionId,approval:session.approval});});
app.post("/api/create-order",async(req,res)=>{const {sessionId}=req.body,session=sessions.get(sessionId);if(!session)return res.status(404).json({error:"Session not found."});if(!session.approval?.approved){auditLog("SECURITY","ORDER_BLOCKED_NO_MERCHANT_APPROVAL",{sessionId});return res.status(403).json({error:"Merchant approval is required before any money action."});}if(session.offer.discountPercent>POLICY.maxDiscountPercent||session.offer.finalAmountPaise>POLICY.maxOfferAmountPaise)return res.status(400).json({error:"Offer exceeds money-action policy."});if(!razorpay){auditLog("PAYMENT","ORDER_SIMULATION",{sessionId,reason:"Razorpay test credentials not configured"});return res.json({simulated:true,order:{id:`sim_${Date.now()}`,amount:session.offer.finalAmountPaise,currency:"INR"}})}try{const order=await razorpay.orders.create({amount:session.offer.finalAmountPaise,currency:"INR",receipt:`pp_${sessionId.replaceAll("-","").slice(0,30)}`,notes:{offerId:session.offer.offerId,sessionId}});session.order=order;auditLog("PAYMENT","RAZORPAY_ORDER_CREATED",{sessionId,orderId:order.id,amount:order.amount,currency:order.currency});res.json({simulated:false,order,keyId:process.env.RAZORPAY_KEY_ID})}catch(error){auditLog("PAYMENT","ORDER_CREATION_FAILED",{sessionId,message:error.message});res.status(502).json({error:"Could not create Razorpay order."})}});
app.post("/api/payment/success",(req,res)=>{const {sessionId,razorpay_payment_id,razorpay_order_id,razorpay_signature}=req.body,session=sessions.get(sessionId);if(!session)return res.status(404).json({error:"Session not found."});let verified=true;if(process.env.RAZORPAY_KEY_SECRET&&razorpay_order_id&&razorpay_payment_id&&razorpay_signature){const expected=crypto.createHmac("sha256",process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest("hex");verified=expected===razorpay_signature}session.payment={status:verified?"SUCCESS":"SIGNATURE_INVALID",paymentId:razorpay_payment_id||null,orderId:razorpay_order_id||null,verified,at:new Date().toISOString()};auditLog("PAYMENT",verified?"PAYMENT_SUCCESS_VERIFIED":"PAYMENT_SIGNATURE_INVALID",{sessionId,paymentId:razorpay_payment_id,orderId:razorpay_order_id});if(!verified)return res.status(400).json({error:"Payment signature verification failed."});res.json({success:true,payment:session.payment});});
app.post("/api/payment/failure",(req,res)=>{const {sessionId,reason}=req.body,session=sessions.get(sessionId);if(!session)return res.status(404).json({error:"Session not found."});const recommendation={title:"Recover the conversion",action:"Offer a fresh checkout attempt without increasing the discount.",why:"The customer reached payment but did not complete it. Preserve margin and reduce friction first.",nextStep:"Retry checkout or offer an alternate payment method."};session.payment={status:"FAILED",reason:reason||"Customer did not complete payment.",at:new Date().toISOString()};auditLog("PAYMENT","PAYMENT_FAILED",{sessionId,reason});auditLog("AI","RECOVERY_RECOMMENDATION_GENERATED",{sessionId,recommendation});res.json({payment:session.payment,recommendation});});
app.get("/api/audit",(_req,res)=>res.json({entries:audit}));app.get("/api/session/:id",(req,res)=>{const session=sessions.get(req.params.id);if(!session)return res.status(404).json({error:"Session not found."});res.json(session)});
app.listen(PORT,HOST,()=>{auditLog("SYSTEM","SERVER_STARTED",{port:PORT,host:HOST});console.log(`PAYPILOT AI running on http://${HOST}:${PORT}`)});